// curated list of BSP-regulated banks operating in the Philippines
export const PH_BANKS = [
  "Al-Amanah Islamic Investment Bank",
  "Asia United Bank (AUB)",
  "Bank of China (Philippines)",
  "Bank of Commerce",
  "Bank of the Philippine Islands (BPI)",
  "BDO Unibank",
  "CARD Bank",
  "China Banking Corporation (Chinabank)",
  "CIMB Bank Philippines",
  "Citibank Philippines",
  "CTBC Bank Philippines",
  "Development Bank of the Philippines (DBP)",
  "East West Banking Corporation (EastWest Bank)",
  "GoTyme Bank",
  "HSBC Philippines",
  "ING Bank Philippines",
  "Land Bank of the Philippines (LandBank)",
  "Maya Bank",
  "Maybank Philippines",
  "Metropolitan Bank & Trust Co. (Metrobank)",
  "Philippine Bank of Communications (PBCOM)",
  "Philippine National Bank (PNB)",
  "Philippine Savings Bank (PSBank)",
  "Philippine Trust Company (Philtrust Bank)",
  "Producers Bank",
  "Rizal Commercial Banking Corporation (RCBC)",
  "Robinsons Bank",
  "Security Bank",
  "Standard Chartered Bank Philippines",
  "Sterling Bank of Asia",
  "Tonik Digital Bank",
  "UnionBank of the Philippines",
  "UnionDigital Bank",
  "UNObank",
] as const;
